name: '[DEBUG] Publish w/NativeAOT'

on:
  workflow_dispatch:

jobs:

  run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
          - os: windows-latest
            rid: win-arm64
          - os: macos-latest
            rid: osx-x64
          - os: macos-latest
            rid: osx-arm64
          - os: ubuntu-latest
            rid: linux-x64
          - os: ubuntu-latest
            rid: linux-arm64

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x.x

      - run: |
          dotnet publish nativeAot \
            -c Release \
            -r ${{ matrix.rid }} \
            -o publish

      - uses: actions/upload-artifact@v6
        with:
          name: ghx-${{ matrix.rid }}
          path: publish/**/*

      - run: |
          # VYaml migration tests

          echo =================
          echo RUN HAS SHELL SET
          echo =================
          if dotnet run -c Release -f net10.0 --project ./src -- \
               test--error--run-has-shell; then
            exit 1
          else
            echo Expected error occurred
          fi

          echo ====================
          echo INPUT HAS NO DEFAULT
          echo ====================
          if dotnet run -c Release -f net10.0 --project ./src -- \
               test--error--input-has-no-default; then
            exit 1
          else
            echo Expected error occurred
          fi

      - run: |
          EXE=publish/ghx
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            EXE=publish/ghx.exe
          fi

          $EXE run sample
