on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:

  dry:
    strategy:
      matrix:
        configuration: [Debug, Release]
        mode: ["", "--cmd", "--wsl"]
        once: ["", "--once"]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
    - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
      with:
        dotnet-version: 10.x.x

    - run: |
        dotnet run -c ${{ matrix.configuration }} -f net10.0 --project ./src -- \
          dry \
          ${{ matrix.mode }} \
          ${{ matrix.once }} \
          sample

  run:
    strategy:
      matrix:
        configuration: [Debug, Release]
        runner: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
    - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
      with:
        dotnet-version: 10.x.x

    - run: |
        dotnet run -c ${{ matrix.configuration }} -f net10.0 --project ./src -- run sample
        dotnet run -c ${{ matrix.configuration }} -f net10.0 --project ./src -- new workflow-template
